config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'static_pages/help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'welcome/index', to: 'welcome#index'
  get 'welcome/page', to: 'welcome#page'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :account_activations, only: [:edit]

end

app/views/layouts/_form.html.erb
<%= form_for(@user, url: signup_path) do |f| %>
<%= render 'shared/error_messages' %>
 <div class="form-group">
  <%= f.label :name, 'Your Name', class:'bmd-label-floating'%>
  <%= f.text_field :name, class: 'form-control' %>
  <span class="bmd-help">Please add your name</span>
</div>
<div class="form-group">
  <%= f.label :email, 'Your Email', class:'bmd-label-floating'%>
  <%= f.email_field :email, class: 'form-control' %>
  <span class="bmd-help">We'll never share your email with anyone else.</span>
</div>
<div class="form-group">
  <%= f.label :password, 'Your Password', class:'bmd-label-floating' %>
  <%= f.password_field :password, class: 'form-control'%>
  <span class="bmd-help">Minimum 6 characters.</span>
</div>
<div class="form-group">
  <%= f.label :password_confirmation, "Confirmation", class:'bmd-label-floating' %>
  <%= f.password_field :password_confirmation, class: 'form-control'%>
  <span class="bmd-help">Confirmation Password.</span>
</div>
<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
      <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">

  </head>
  <body>
    <!-- Kube JS (optional if you are using Kube CSS only) -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="#"> <font color="white">NCLINK</font> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%=link_to "Home", root_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
      <%=link_to "Help", static_pages_help_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%=link_to "About", about_path, class:'nav-link' %>
      </li>
      <% if logged_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <%= link_to "Users", users_path, class:'nav-link' %>
        </li>
        </ul>
    </ul>


    <ul class="navbar-nav ml-auto nav-flex-icons">

     <li class="nav-item dropdown">
       <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true"
         aria-expanded="false">
         <i class="zmdi zmdi-flower-alt mdc-text-red"></i> Profile

       </a>
       <div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
         <%= link_to "Settings", edit_user_path(current_user), class:'dropdown-item' %>
         <div class="dropdown-divider"></div>
         <%= link_to "Log out", logout_path, method: "delete", class:'dropdown-item' %>

       </div>
     </li>
   </ul>

    <% else %>
    <ul class="navbar-nav ml-auto nav-flex-icons">

     <li class="nav-item dropdown">
       <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true"
         aria-expanded="false">
         <i class="zmdi zmdi-flower-alt mdc-text-red"></i> Login

       </a>
       <div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
         <%=link_to "Sign Up", users_new_path, class:'dropdown-item' %>
           <div class="dropdown-divider"></div>
         <%= link_to "Log in", login_path, class:'dropdown-item' %>

       </div>
     </li>
   </ul>
      <% end %>

  </div>

</nav>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
<script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
  </body>
</html>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/
html5.min.js">
</script>
<![endif]-->

app/views/layouts/_show.html.erb
<h1>this is swap render it doesnt bring the main render page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kube</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
    <%= render 'layouts/header' %>
    <br>
    <body>
      <div class="container">
        <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type} warning alert-dismissible fade show") %>
      </div>
      <% end %>
      <%= yield %>
        <%= render 'layouts/footer' %>
  </body>
</html>